
package Vista;

import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Victor
 */
public class VistaPrincipalSistema extends javax.swing.JFrame {
    
    private final String[] imagenes = {
        "/Vista/RecursosGraficos/Fondos/Fondo1.jpg",
        "/Vista/RecursosGraficos/Fondos/Fondo2.jpg",
        "/Vista/RecursosGraficos/Fondos/Fondo3.jpg",
        "/Vista/RecursosGraficos/Fondos/Fondo4.jpg"
    };

    private int indiceImagenActual = 0;
    private Timer timer;

    private JPanel panelPrincipal;

    /**
     * Creates new form VistaPrincipalSistema
     */
    public VistaPrincipalSistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Vista/RecursosGraficos/IconoPrograma.png")).getImage());
        
        timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cambiarImagen();
            }
        });
        timer.start();
    }
    
    private void cambiarImagen() {
        indiceImagenActual = (indiceImagenActual + 1) % imagenes.length;
        panelPrincipal.repaint();
    }
    
    /* utiles para presentar por netbeans
    panelPrincipal = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(getClass().getResource(imagenes[indiceImagenActual]));
                g.drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(), this);
            }
        };
    
    MenuPrincipal.setLayout(new FlowLayout(FlowLayout.CENTER));

        MenuSga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/MenuBar/Alumno.png"))); // NOI18N
        MenuSga.setText("SGA");
        MenuSga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuSga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MenuSga.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MenuSga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSgaMouseClicked(evt);
            }
        });
        MenuPrincipal.add(MenuSga);
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(getClass().getResource(imagenes[indiceImagenActual]));
                g.drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(), this);
            }
        };

        MenuPrincipal = new javax.swing.JMenuBar();
        MenuSga = new javax.swing.JMenu();
        MenuPersonal = new javax.swing.JMenu();
        MenuAcerca = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNIVERSIDAD NACIONAL DE LOJA");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        MenuPrincipal.setLayout(new FlowLayout(FlowLayout.CENTER));

        MenuSga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/MenuBar/Alumno.png"))); // NOI18N
        MenuSga.setText("SGA");
        MenuSga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuSga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MenuSga.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MenuSga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSgaMouseClicked(evt);
            }
        });
        MenuPrincipal.add(MenuSga);

        MenuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/MenuBar/Personal.png"))); // NOI18N
        MenuPersonal.setText("PERSONAL ADMINISTRATIVO");
        MenuPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MenuPersonal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MenuPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPersonalMouseClicked(evt);
            }
        });
        MenuPrincipal.add(MenuPersonal);

        MenuAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/MenuBar/Acerca.png"))); // NOI18N
        MenuAcerca.setText("ACERCA DE LA UNVERSIDAD");
        MenuAcerca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuAcerca.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MenuAcerca.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MenuAcerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAcercaMouseClicked(evt);
            }
        });
        MenuPrincipal.add(MenuAcerca);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSgaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSgaMouseClicked
        
        VistaInicioSesion vi = new VistaInicioSesion();
        vi.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_MenuSgaMouseClicked

    private void MenuPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPersonalMouseClicked
        
        VistaInicioSesionPersonal vi = new VistaInicioSesionPersonal();
        vi.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_MenuPersonalMouseClicked

    private void MenuAcercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAcercaMouseClicked
        
        VistaInicioSesion vi = new VistaInicioSesion();
        vi.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_MenuAcercaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipalSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAcerca;
    private javax.swing.JMenu MenuPersonal;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuSga;
    //private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
