
package Vista;

import Controlador.Dao.Modelo.cursoDao;
import Controlador.Dao.Modelo.horarioDao;
import Controlador.Dao.Modelo.presentacionDao;
import Controlador.TDA.ListaDinamica.Excepcion.ListaVacia;
import Controlador.TDA.ListaDinamica.ListaDinamica;
import Modelo.ControlAccesoDocente;
import Modelo.Cursa;
import Modelo.Horario;
import Modelo.Presentacion;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author romer
 */
public class VistaDocentePrincipal extends javax.swing.JFrame {
    presentacionDao presentacionControlDao = new presentacionDao();
    private ListaDinamica<Presentacion> listaPresentacion = presentacionControlDao.all();
    private ListaDinamica<String> imagenes = new ListaDinamica<>();
    
//    private final String[] imagenes = {
//        "/Vista/RecursosGraficos/Fondos/Fondo1.jpg",
//        "/Vista/RecursosGraficos/Fondos/Fondo2.jpg",
//        "/Vista/RecursosGraficos/Fondos/Fondo3.jpg",
//        "/Vista/RecursosGraficos/Fondos/Fondo4.jpg"
//    };

    private int indiceImagenActual = -1;
    private Timer timer;

    /**
     * Creates new form VistaDocentes
     * @throws Controlador.TDA.ListaDinamica.Excepcion.ListaVacia
     */
    public VistaDocentePrincipal() throws ListaVacia {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Vista/RecursosGraficos/IconoPrograma.png")).getImage());
        
        mostrarNombreDocente();
        
        for (int i = 0; i < listaPresentacion.getLongitud(); i++) {
            try {
                String imagen = listaPresentacion.getInfo(i).getImagen();
                imagenes.Agregar(imagen);
            } 
            catch (ListaVacia ex) {
                
            }
        }

        cambiarImagen();
  
        timer = new Timer(2500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    cambiarImagen();
                } 
                catch (ListaVacia ex) {

                }
            }
        });
        timer.start();
    }
    
    private String CargarImagen() throws ListaVacia {
        try {
            String rutaImagen = imagenes.getInfo(indiceImagenActual);
            if (rutaImagen.startsWith("src/")) {
                rutaImagen = rutaImagen.substring(3);
            }
            return rutaImagen;
        }
        catch (NullPointerException e) {
            e.printStackTrace();
            return "";
        }
    }

    private void cambiarImagen() throws ListaVacia {
        int intentos = 0;
        do {
            indiceImagenActual = (indiceImagenActual + 1) % imagenes.getLongitud();
            intentos++;
        } 
        while (!"Activa".equalsIgnoreCase(listaPresentacion.getInfo(indiceImagenActual).getEstadoPresentacion()) && intentos < imagenes.getLongitud());

        panelPrincipal.repaint(); 
    }
 
    private void mostrarNombreDocente() {
        String nombreDocente = ControlAccesoDocente.getNombreDocenteLogeado();
        lblNombreUsuarioIngresado.setText(nombreDocente);
    }

    /*
     * panelPrincipal = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(getClass().getResource(imagenes[indiceImagenActual]));
                g.drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(), this);
            }
        };
     * 
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                try {
                    ImageIcon icon = new ImageIcon(getClass().getResource(CargarImagen()));
                    g.drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(), this);
                } 
                catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelPresentacion = new Vista.Utiles.BordesRedondos();
        jLabel1 = new javax.swing.JLabel();
        lblNombreUsuarioIngresado = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnAsistencias = new javax.swing.JButton();
        btnCalendario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VISTA GENERAL DOCENTE");
        setBackground(new java.awt.Color(172, 174, 185));

        jPanel3.setBackground(new java.awt.Color(61, 90, 134));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/LojoUNL.png"))); // NOI18N

        PanelPresentacion.setBackground(new java.awt.Color(0, 0, 0, 10));
        PanelPresentacion.setRoundBottomLeft(40);
        PanelPresentacion.setRoundBottomRight(40);
        PanelPresentacion.setRoundTopLeft(40);
        PanelPresentacion.setRoundTopRight(40);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        lblNombreUsuarioIngresado.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblNombreUsuarioIngresado.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuarioIngresado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreUsuarioIngresado.setText(" ");

        javax.swing.GroupLayout PanelPresentacionLayout = new javax.swing.GroupLayout(PanelPresentacion);
        PanelPresentacion.setLayout(PanelPresentacionLayout);
        PanelPresentacionLayout.setHorizontalGroup(
            PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPresentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPresentacionLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblNombreUsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        PanelPresentacionLayout.setVerticalGroup(
            PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPresentacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreUsuarioIngresado)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel3)
                .addGap(70, 70, 70)
                .addComponent(PanelPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PanelPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegresar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/Botones/CerraSesion.png"))); // NOI18N
        btnRegresar.setText("CERRAR SESION");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAsistencias.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/Botones/Asistencia.png"))); // NOI18N
        btnAsistencias.setText("ASISTENCIAS");
        btnAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciasActionPerformed(evt);
            }
        });

        btnCalendario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/Botones/Calendario.png"))); // NOI18N
        btnCalendario.setText("CALENDARIO");
        btnCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 732, Short.MAX_VALUE)
                .addComponent(btnAsistencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalendario)
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 524, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalendario)
                    .addComponent(btnRegresar)
                    .addComponent(btnAsistencias))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        try {
            int result = JOptionPane.showConfirmDialog(null, "Estas seguro que quieres cerrar sesion?", "CONFIRMAR CIERRE DE SESION", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {
                VistaPrincipalSistema abrirLogin = new VistaPrincipalSistema();
                abrirLogin.setVisible(true);
                this.setVisible(false);
            }
        } 
        catch (Exception e) {
            
        }
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciasActionPerformed

        try {
            VistaDocentesTomaAsistencia vta = new VistaDocentesTomaAsistencia();
            vta.setVisible(true);
            this.setVisible(false);
        }
        catch (Exception e) {

        }
    }//GEN-LAST:event_btnAsistenciasActionPerformed

    private void btnCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioActionPerformed
        
        try {
            VistaCalendarioDocente c = new VistaCalendarioDocente();
            horarioDao HD = new horarioDao();
            cursoDao cursaControlDao = new cursoDao();

            int idDocenteLogeado = ControlAccesoDocente.getIdDocenteLogeado();

            ListaDinamica<Horario> listaHorarios = HD.all();
            ListaDinamica<Cursa> listaCursas = cursaControlDao.all();

            for (int i = 0; i < listaHorarios.getLongitud(); i++) {
                Horario horario = listaHorarios.getInfo(i);
                int idMateriaHorario = horario.getMateriaHorario().getIdMateria();

                for (int j = 0; j < listaCursas.getLongitud(); j++) {
                    Cursa cursa = listaCursas.getInfo(j);
                    int idDocenteMateria = cursa.getDocenteCursa().getIdDocente();

                    if (idDocenteMateria == idDocenteLogeado && idMateriaHorario == cursa.getMateriaCursa().getIdMateria()) {
                        String diaSemana = horario.getDiaSemana();

                        String nombreMateria = cursa.getMateriaCursa().getNombreMateria();
                        String cicloMateria = cursa.getMateriaCursa().getCicloMateria().getNombreCiclo().getNombreCiclo();
                        String paraleloMateria = cursa.getParaleloCursa().getNombre();
                        String horaInicio = horario.getHoraIncio();
                        String horaFin = horario.getHoraFin();
                        String mensaje = nombreMateria + " " + cicloMateria + " "+ paraleloMateria + " "+ horaInicio + " - " + horaFin;

                        c.AgregarEvento(diaSemana, mensaje);
                    }
                }
            }
            c.setVisible(true);
            this.setVisible(false);
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btnCalendarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDocentePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDocentePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDocentePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDocentePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaDocentePrincipal().setVisible(true);
                } 
                catch (ListaVacia ex) {
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.Utiles.BordesRedondos PanelPresentacion;
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnCalendario;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblNombreUsuarioIngresado;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
