
package Vista;

import Controlador.Dao.Modelo.cursoDao;
import Controlador.Dao.Modelo.horarioDao;
import Controlador.Dao.Modelo.matriculaDao;
import Controlador.TDA.ListaDinamica.ListaDinamica;
import Modelo.ControlAccesoAlumno;
import Modelo.Cursa;
import Modelo.Horario;
import Modelo.Materia;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Victor
 */
public class VistaAlumnoPrincipal extends javax.swing.JFrame {
    horarioDao horarioControlDao = new horarioDao();;
    cursoDao cursaControlDao = new cursoDao();
    matriculaDao matriculaControlDao = new matriculaDao();
    
    private final String[] imagenes = {
        "/Vista/RecursosGraficos/Fondos/Fondo1.jpg",
        "/Vista/RecursosGraficos/Fondos/Fondo2.jpg",
        "/Vista/RecursosGraficos/Fondos/Fondo3.jpg",
        "/Vista/RecursosGraficos/Fondos/Fondo4.jpg"
    };

    private int indiceImagenActual = 0;
    private Timer timer;

    /**
     * Creates new form VistaAlumnoPrincipal
     */
    public VistaAlumnoPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Vista/RecursosGraficos/IconoPrograma.png")).getImage());
        cargarMateriasAlumno();
        mostrarNombreDocente();
        timer = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cambiarImagen();
            }
        });
        timer.start();
    }
    
    private void cambiarImagen() {
        indiceImagenActual = (indiceImagenActual + 1) % imagenes.length;
        panelPrincipal.repaint();
    }

    private void cargarMateriasAlumno() {
        int idAlumnoLogeado = ControlAccesoAlumno.getIdAlumnoLogeado();
        cbxMateriaAlumno.removeAllItems();

        try {
            ListaDinamica<Cursa> listaCursas = obtenerCursasPorAlumno(idAlumnoLogeado);

            for (Cursa cursa : listaCursas.toArray()) {
                Materia materia = cursa.getMateriaCursa();
                if (materia != null) {
                    cbxMateriaAlumno.addItem(materia.getNombreMateria());
                }
            }
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    public ListaDinamica<Cursa> obtenerCursasPorAlumno(int idAlumno) {
        ListaDinamica<Cursa> cursasPorAlumno = new ListaDinamica<>();
        ListaDinamica<Cursa> listaMaterias = cursaControlDao.all();

        for (Cursa cursa : listaMaterias.toArray()) {
            if (cursa.getMatriculaCursa().getAlumnoMatricula().getIdAlumno() == idAlumno) {
                cursasPorAlumno.Agregar(cursa);
            }
        }
        return cursasPorAlumno;
    }
    
    private void mostrarNombreDocente() {
        String nombreDocente = ControlAccesoAlumno.getNombreAlumnoLogeado();
        lblNombreAlumnoIngresado.setText(nombreDocente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(getClass().getResource(imagenes[indiceImagenActual]));
                g.drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(), this);
            }
        };
        
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelPresentacion = new Vista.Utiles.BordesRedondos();
        jLabel1 = new javax.swing.JLabel();
        lblNombreAlumnoIngresado = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        bordesRedondos1 = new Vista.Utiles.BordesRedondos();
        cbxMateriaAlumno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        bordesRedondos2 = new Vista.Utiles.BordesRedondos();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VISTA GENERAL ALUMNO");

        jPanel3.setBackground(new java.awt.Color(61, 90, 134));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/LojoUNL.png"))); // NOI18N

        PanelPresentacion.setBackground(new java.awt.Color(0, 0, 0, 10));
        PanelPresentacion.setRoundBottomLeft(40);
        PanelPresentacion.setRoundBottomRight(40);
        PanelPresentacion.setRoundTopLeft(40);
        PanelPresentacion.setRoundTopRight(40);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        lblNombreAlumnoIngresado.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblNombreAlumnoIngresado.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAlumnoIngresado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreAlumnoIngresado.setText(" ");

        javax.swing.GroupLayout PanelPresentacionLayout = new javax.swing.GroupLayout(PanelPresentacion);
        PanelPresentacion.setLayout(PanelPresentacionLayout);
        PanelPresentacionLayout.setHorizontalGroup(
            PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPresentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreAlumnoIngresado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelPresentacionLayout.setVerticalGroup(
            PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPresentacionLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreAlumnoIngresado))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(PanelPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PanelPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegresar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/Botones/CerraSesion.png"))); // NOI18N
        btnRegresar.setText("CERRAR SESION");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        bordesRedondos1.setBackground(new java.awt.Color(0, 0, 0, 30));
        bordesRedondos1.setRoundBottomLeft(50);
        bordesRedondos1.setRoundBottomRight(50);
        bordesRedondos1.setRoundTopLeft(50);
        bordesRedondos1.setRoundTopRight(50);

        jLabel2.setFont(new java.awt.Font("Century", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MATERIA");

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/Botones/PorcentajeAsistencia.png"))); // NOI18N
        jButton3.setText("VER MATERIA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bordesRedondos1Layout = new javax.swing.GroupLayout(bordesRedondos1);
        bordesRedondos1.setLayout(bordesRedondos1Layout);
        bordesRedondos1Layout.setHorizontalGroup(
            bordesRedondos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bordesRedondos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bordesRedondos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(cbxMateriaAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bordesRedondos1Layout.setVerticalGroup(
            bordesRedondos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bordesRedondos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMateriaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(19, 19, 19))
        );

        bordesRedondos2.setBackground(new java.awt.Color(0, 0, 0,30));
        bordesRedondos2.setRoundBottomLeft(50);
        bordesRedondos2.setRoundBottomRight(50);
        bordesRedondos2.setRoundTopLeft(50);
        bordesRedondos2.setRoundTopRight(50);

        jLabel4.setFont(new java.awt.Font("Century", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CALENDARIO");

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/RecursosGraficos/Botones/Calendario.png"))); // NOI18N
        jButton1.setText("CALENDARIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bordesRedondos2Layout = new javax.swing.GroupLayout(bordesRedondos2);
        bordesRedondos2.setLayout(bordesRedondos2Layout);
        bordesRedondos2Layout.setHorizontalGroup(
            bordesRedondos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bordesRedondos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bordesRedondos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bordesRedondos2Layout.setVerticalGroup(
            bordesRedondos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bordesRedondos2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bordesRedondos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(bordesRedondos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bordesRedondos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bordesRedondos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(142, 142, 142)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        try {
            int result = JOptionPane.showConfirmDialog(null, "Estas seguro que quieres cerrar sesion?", "CONFIRMAR CIERRE DE SESION", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {
                VistaPrincipalSistema abrirLogin = new VistaPrincipalSistema();
                abrirLogin.setVisible(true);
                this.setVisible(false);
            }
        }
        catch (Exception e) {

        }

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            VistaCalendarioAlumno vistaCalendarioAlumno = new VistaCalendarioAlumno();

            Integer idAlumnoLogeado = ControlAccesoAlumno.getIdAlumnoLogeado();
            if (idAlumnoLogeado != null) {
                ListaDinamica<Horario> listaHorarios = horarioControlDao.all();
                ListaDinamica<Cursa> listaCursas = cursaControlDao.all();

                for (int i = 0; i < listaHorarios.getLongitud(); i++) {
                    Horario horario = listaHorarios.getInfo(i);
                    int idMateriaHorario = horario.getMateriaHorario().getIdMateria();

                    for (int j = 0; j < listaCursas.getLongitud(); j++) {
                        Cursa cursa = listaCursas.getInfo(j);
                        int idAlumnoCursa = cursa.getMatriculaCursa().getAlumnoMatricula().getIdAlumno();

                        if (idAlumnoCursa == idAlumnoLogeado && idMateriaHorario == cursa.getMateriaCursa().getIdMateria()) {
                            String diaSemana = horario.getDiaSemana();
                            String nombreMateria = cursa.getMateriaCursa().getNombreMateria();
                            String cicloMateria = cursa.getMateriaCursa().getCicloMateria().getNombreCiclo().getNombreCiclo();
                            String paraleloMateria = cursa.getParaleloCursa().getNombre();
                            String horaInicio = horario.getHoraIncio();
                            String horaFin = horario.getHoraFin();
                            String mensaje = nombreMateria + " - " + cicloMateria + " - " + paraleloMateria + " - " + horaInicio + " - " + horaFin;

                            vistaCalendarioAlumno.AgregarEvento(diaSemana, mensaje);
                        }
                    }
                }
                vistaCalendarioAlumno.setVisible(true);
                this.setVisible(false);
            } 
            else {
                System.out.println("No hay alumno logeado en este momento.");
            }
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        VistaAlumnoMaterias vm = new VistaAlumnoMaterias();
        vm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAlumnoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.Utiles.BordesRedondos PanelPresentacion;
    private Vista.Utiles.BordesRedondos bordesRedondos1;
    private Vista.Utiles.BordesRedondos bordesRedondos2;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Object> cbxMateriaAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblNombreAlumnoIngresado;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
